---

- name: Configure broadcasting host
  hosts: vm1
  become: true
  gather_facts: true
  roles:
    - role: arp-flag-broadcaster
      decoy_ip: 192.168.25.99
      decoy_port: 4444
      flag_value: "{{ flag }}"

- name: Provision attacker workstation
  hosts: vma
  become: true
  gather_facts: true
  roles:
    - role: user-access
      user_access_username: user
      user_access_password: 'Password123'
      user_access_sudo: true
